export default {
  LOAD_ALL_CALENDARS: 'LOAD_ALL_CALENDARS',
  LOAD_ALL_CALENDARS_FULFILLED: 'LOAD_ALL_CALENDARS_FULFILLED',

  LOAD_CALENDAR_BY_ID: 'LOAD_CALENDAR_BY_ID',
  LOAD_CALENDAR_BY_ID_FULFILLED: 'LOAD_CALENDAR_BY_ID_FULFILLED',

  LOAD_CALENDAR: 'LOAD_CALENDAR',
  LOAD_CALENDAR_FULFILLED: 'LOAD_CALENDAR_FULFILLED',

  ADD_CALENDAR: 'ADD_CALENDAR',
  ADD_CALENDAR_FULFILLED: 'ADD_CALENDAR_FULFILLED',

  SCHEDULE_MEETING: 'SCHEDULE_MEETING',
  SCHEDULE_MEETING_FULFILLED: 'SCHEDULE_MEETING_FULFILLED',
  
  API_BASE: "https://ggs61ptt6k.execute-api.us-east-2.amazonaws.com/dev"
}