export default {
  LOAD_ALL_CALENDARS: 'LOAD_ALL_CALENDARS',
  LOAD_ALL_CALENDARS_FULFILLED: 'LOAD_ALL_CALENDARS_FULFILLED',
  LOAD_CALENDAR: 'LOAD_CALENDAR',
  LOAD_CALENDAR_FULFILLED: 'LOAD_CALENDAR_FULFILLED'
}